### ISSUE TITLE
Error when startign server

### ISSUE THREAD

**Issue by ghost** [Fallingsheep1985/ExPack_0.01_Fresh_Jeans#3]
sorry was my fail -.-

**Comment by UtraTM** [comment]
if ((_pos distance _testPos) >= _minDist) the>
18:51:12   Error position: <_pos distance _testPos) >= _minDist) the>
18:51:12   Error Undefined variable in expression: _pos
18:51:12 File A3\functions_f\misc\fn_findSafePos.sqf, line 98
18:51:12 Error in expression <["_newX", "_newY", "_testPos"];
_newX = _posX + (_maxDist - (random (_maxDist * >
18:51:12   Error position: <_posX + (_maxDist - (random (_maxDist * >
18:51:12   Error Undefined variable in expression: _posx
18:51:12 File A3\functions_f\misc\fn_findSafePos.sqf, line 90
18:51:12 Error in expression < BIS_fnc_isPosBlacklisted)) then
